# The "Operator" configuration contains a ACL that has access to the "Team-Server" only.
#
#You may notice there is a IP_FROM_LINODE place-holder as well, but this will be addressed during the build process with a sed command.

pki:
  ca: C:\dev\C2Spawn\templates\certificates\ca.crt
  cert: C:\dev\C2Spawn\templates\certificates\operator.crt
  key: C:\dev\C2Spawn\templates\certificates\operator.key

static_host_map:
  "192.168.100.1": ["LIGHTHOUSE_IP_ADDRESS:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.168.100.1"

listen:
  host: 0.0.0.0
  port: 4242

tun:
  # sensible defaults. don't monkey with these unless
  # you're CERTAIN you know what you're doing.
  #
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: icmp
      host: any

    - port: any
      proto: any
      group: team-server

  inbound:
    - port: any
      proto: icmp
      host: any

    - port: any
      proto: any
      group: team-server

