# The "Internal-Redirectors" configuration contains a ACL that allows traffic from both the edge and team-server groups.
#  This is because the "Internal-Redirectors" are responsible for moving data from the "Edge-Redirectors" to the "Team-Server

pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key

static_host_map:
  "192.168.100.1": ["LIGHTHOUSE_IP_ADDRESS:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.168.100.1"

listen:
  host: 0.0.0.0
  port: 4242

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: icmp
      host: any

    - port: any
      proto: any
      group: edge

    - port: any
      proto: any
      group: team-server

  inbound:
    - port: any
      proto: icmp
      host: any

    - port: any
      proto: any
      group: edge

    - port: any
      proto: any
      group: team-server